name: Python Lint

on:
  push:
    branches:
      - "**"   # run on all branches
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install black==24.4.2
      - name: Run black (check mode)
        run: black --check .
